### ISSUE TITLE
Exception: Could not locate slingshot

### ISSUE THREAD

**Issue by leblowl** [xsc/ancient-clj#7]
```clojure.lang.ExceptionInfo: Could not locate slingshot/slingshot__init.class or slingshot/slingshot.clj on classpath: 
    data: {:file "clj_http/client.clj", :line 1}```

This is for the latest version 0.3.9. There isn't an issue in 0.3.8.

**Comment by leblowl** [comment]
awesome lib btw!

**Comment by xsc** [comment]
Could you paste the output of the following?

```
lein deps :tree | grep clj-http
```

The version of `clj-http` used by `ancient-clj` has `slingshot` only as an optional dependency, so you might want to upgrade the one you're using. Or alternatively, add `slingshot` directly to your `project.clj`.

**Comment by leblowl** [comment]
Well I'm using the boot build tool. So I think ```boot show -d | grep clj-http``` is an equivalent command. Without slingshot added directly, I get the same error when I run the above command. With slingshot added directly, I get: ```├── clj-http "1.1.0" :exclusions [[joda-time] [org.clojure/clojure] [com.cognitect/transit-clj] [crouton] [slingshot]]```.

I'm fine with just adding it directly at the moment. ty
